### ISSUE TITLE
[BUG] Docker repositories for public consumption

### ISSUE THREAD

**Issue by imyousuf** [newscred/webhook-broker#128]
**Describe the bug**
The current docker container repositories of webhook broker is dockerhub and github; both are individual to `imyousuf`; we need to move them to something owned by Opti.

**Additional context**
This is a result of repo ownership change.

**Comment by pratikjoy7** [comment]
We have created a public ECR repository for webhook-broker - https://gallery.ecr.aws/optimizely/webhook-broker

As well as a public helm repo - `optimizely-helm-charts/public/`
